project:
  name: storm
  version: 1.0.0
  license: Apache-2
  desc: ...
fmt:
  - go fmt ./...
  - goimports .
lint:
  - go vet ./...
  - golangci-lint run --enable-all
  - checklicense
generate:
  - go generate
  - go-bindata ...
  - addlicenses
  - changelog
test:
  - go test ./...
coverage:
  - go cover ...
build:
#   binaries:
#     - name: tool1
#       path: ./cmd/tool1
#     - name: tool2
#       path: ./cmd/tool2
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  flags: |
    -a
    -installsuffix cgo
  ldflags: |
    -s
    -w
    -X "main.BuildVersion={{.Version}}"
    -X "main.BuildInfo={{.BuildInfo}}"
    -extldflags '-static'
  platforms:
    - linux/amd64
    - darwin/amd64
  hooks:
    before:
      - go mod download
    after:
      - ...
package:
  tarball:
    includes:
      - docs/*.md
      - LICENSE
  rpm:
    prefix: /usr/local/bin
    requires:
    provides:
  deb:
    prefix: /usr/local/bin
checksum:
  algo: sha256
  single-file: checksums.txt
release:
  github:
    token: "{{ .Env.GITHUB_TOKEN }}"
  bintray:
    path: user/repo/latest/xxx
    token: "{{ .Env.BINTRAY_TOKEN }}"
  brew:
    repo: github.com/subchen/homebrew-tap
    token: "{{ .Env.GITHUB_TOKEN }}"
    folder: Formula
  docker:
    registry: hub.docker.io
    username: "{{ .Env.DOCKER_USERNAME }}"
    password: "{{ .Env.DOCKER_PASSWORD }}"
    dockerfile: Dockerfile
    image: subchen/gomk
    tags:
      - latest
      - "{{.Version}}"
    args:
      - arg1=value1
      - arg2=value2

