[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  name = "github.com/subchen/go-cli"
  version = "2.0.0"

[[constraint]]
  name = "github.com/subchen/go-log"
  version = "3.0.0"

[[constraint]]
  name = "github.com/subchen/go-stack"
  branch = "master"

[[constraint]]
  name = "github.com/subchen/go-tableify"
  version = "1.1.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
